import {APP_VERSION,BACKUP_REMINDER_DAYS,ENTITY_STORES,PLACE_TYPES,PHOTO_JPEG_QUALITY,PHOTO_MAX_EDGE,backupAgeDays,backupReminderDue,buildBackupEnvelope,createVersioned,fitWithin,groupTasksForToday,makeOutboxMutation,migrateLegacyFieldRecord,migrateLegacyOutboxMutation,newId,nextRepeatDue,normalizeRepeat,sortTimeline,updateVersioned} from './core.mjs';
import {CROP_CATEGORIES,CROP_VISUALS,almanacCard,almanacLabel,buildAgProvenance,applicationRecord,cropRotation,farmToday,fieldIntelligence,fieldSeasonHistory,frostContext,historyComparisonNote,normalizeCrop,normalizeYield,seasonWeatherSummary,yieldTrend,polygonAreaAcres,sourceFreshness,sprayWeatherFlags,validateScout,weatherSnapshot} from './ag-intel.mjs';
import {designFieldExperiment,predictiveR2} from './predictive.mjs';
import {nwsPeriodToSnapshot,nwsPointForecast,providerStatus} from './providers.mjs';
import {createFarmMap,fieldCollection,setBasemap,setCropContext,setSlopeOverlay,setSoilOverlay,setWaterOverlay,setBoundaryDraft,canAppendBoundaryPoint,boundarySelfIntersects} from './map-engine.mjs';
const DB_NAME='cropchronicle',DB_VERSION=6,STORES=['profile','farms','places','boundaries','seasons','observations','ag_samples','harvests','applications','experiments','weather_snapshots','reference_layers','sharing','events','media','tasks','outbox'];
const db=await openDb();
const $=(s)=>document.querySelector(s);
const state={farmId:null,placeId:null,wizardStep:0,wizardSteps:[],view:'map',boundaryDraft:[],boundaryEditing:false,location:null,geoMap:null,mapFeatures:null,basemap:'usgs_imagery',soilOverlay:false,cropContext:false,slopeOverlay:false,waterOverlay:false};
for(const id of ['soilLayerToggle','cropContextToggle','slopeLayerToggle','waterLayerToggle']){const el=document.getElementById(id);if(el)el.checked=false;}
const now=()=>new Date().toISOString();
let toastTimer;

function openDb(){
  return new Promise((resolve,reject)=>{
    const r=indexedDB.open(DB_NAME,DB_VERSION);
    r.onupgradeneeded=(event)=>{
      const d=r.result,tx=r.transaction;
      const ensure=(name,options)=>d.objectStoreNames.contains(name)?tx.objectStore(name):d.createObjectStore(name,options);
      ensure('profile',{keyPath:'id'});
      ensure('farms',{keyPath:'id'});
      const places=ensure('places',{keyPath:'id'});
      if(!places.indexNames.contains('farmId'))places.createIndex('farmId','farmId');
      if(!places.indexNames.contains('type'))places.createIndex('type','type');
      const boundaries=ensure('boundaries',{keyPath:'id'});
      if(!boundaries.indexNames.contains('placeId'))boundaries.createIndex('placeId','placeId',{unique:true});
      const seasons=ensure('seasons',{keyPath:'id'});
      if(!seasons.indexNames.contains('placeId'))seasons.createIndex('placeId','placeId');
      const observations=ensure('observations',{keyPath:'id'});if(!observations.indexNames.contains('placeId'))observations.createIndex('placeId','placeId');
      const samples=ensure('ag_samples',{keyPath:'id'});if(!samples.indexNames.contains('placeId'))samples.createIndex('placeId','placeId');
      const experiments=ensure('experiments',{keyPath:'id'});if(!experiments.indexNames.contains('placeId'))experiments.createIndex('placeId','placeId');if(!experiments.indexNames.contains('farmId'))experiments.createIndex('farmId','farmId');const applications=ensure('applications',{keyPath:'id'});if(!applications.indexNames.contains('placeId'))applications.createIndex('placeId','placeId');if(!applications.indexNames.contains('farmId'))applications.createIndex('farmId','farmId');const harvests=ensure('harvests',{keyPath:'id'});if(!harvests.indexNames.contains('placeId'))harvests.createIndex('placeId','placeId');if(!harvests.indexNames.contains('farmId'))harvests.createIndex('farmId','farmId');const weather=ensure('weather_snapshots',{keyPath:'id'});if(!weather.indexNames.contains('farmId'))weather.createIndex('farmId','farmId');const refs=ensure('reference_layers',{keyPath:'id'});if(!refs.indexNames.contains('farmId'))refs.createIndex('farmId','farmId');const sharing=ensure('sharing',{keyPath:'id'});if(!sharing.indexNames.contains('placeId'))sharing.createIndex('placeId','placeId',{unique:true});
      const events=ensure('events',{keyPath:'id'});
      if(!events.indexNames.contains('placeId'))events.createIndex('placeId','placeId');
      const media=ensure('media',{keyPath:'id'});
      if(!media.indexNames.contains('placeId'))media.createIndex('placeId','placeId');
      if(!media.indexNames.contains('eventId'))media.createIndex('eventId','eventId');
      const tasks=ensure('tasks',{keyPath:'id'});
      if(!tasks.indexNames.contains('placeId'))tasks.createIndex('placeId','placeId');
      if(!tasks.indexNames.contains('dueDate'))tasks.createIndex('dueDate','dueDate');
      const outboxStore=ensure('outbox',{keyPath:'mutationId'});

      if(event.oldVersion<2){
        if(d.objectStoreNames.contains('fields')){
          const legacy=tx.objectStore('fields');
          legacy.openCursor().onsuccess=(e)=>{
            const c=e.target.result;
            if(!c)return;
            places.put(migrateLegacyFieldRecord(c.value));
            c.continue();
          };
        }
        for(const name of ['boundaries','seasons','events','media']){
          if(!d.objectStoreNames.contains(name))continue;
          const store=tx.objectStore(name);
          store.openCursor().onsuccess=(e)=>{
            const c=e.target.result;
            if(!c)return;
            const value=c.value;
            if(!value.placeId&&value.fieldId)c.update({...value,placeId:value.fieldId});
            c.continue();
          };
        }
        outboxStore.openCursor().onsuccess=(e)=>{
          const c=e.target.result;
          if(!c)return;
          c.update(migrateLegacyOutboxMutation(c.value));
          c.continue();
        };
      }
    };
    r.onblocked=()=>reject(new Error('CropChronicle update is blocked by another open tab. Close other CropChronicle tabs and reopen.'));
    r.onsuccess=()=>{
      const opened=r.result;
      opened.onversionchange=()=>opened.close();
      resolve(opened);
    };
    r.onerror=()=>reject(r.error);
  });
}
function req(r){return new Promise((resolve,reject)=>{r.onsuccess=()=>resolve(r.result);r.onerror=()=>reject(r.error);});}
function done(tx){return new Promise((resolve,reject)=>{tx.oncomplete=resolve;tx.onerror=()=>reject(tx.error);tx.onabort=()=>reject(tx.error??new Error('IndexedDB transaction aborted.'));});}
async function all(store){const tx=db.transaction(store);return req(tx.objectStore(store).getAll());}
async function one(store,id){const tx=db.transaction(store);return req(tx.objectStore(store).get(id));}
async function byIndex(store,index,value){const tx=db.transaction(store);return req(tx.objectStore(store).index(index).getAll(value));}
async function putProfile(record){const tx=db.transaction('profile','readwrite');tx.objectStore('profile').put(record);await done(tx);}
async function putWithOutbox(entityType,entity,{operation='create',baseVersion=null}={}){const store=ENTITY_STORES[entityType];const mutation=makeOutboxMutation(entityType,entity,operation,baseVersion);const tx=db.transaction([store,'outbox'],'readwrite');tx.objectStore(store).put(entity);tx.objectStore('outbox').put(mutation);await done(tx);return mutation;}
function notifySaved(){const el=$('#saveToast');el.hidden=false;clearTimeout(toastTimer);toastTimer=setTimeout(()=>{el.hidden=true;},2200);}
function localDateOnly(d=new Date()){return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`;}
function placeTypeLabel(type){return type==='herd/pen'?'Herd / pen':type.charAt(0).toUpperCase()+type.slice(1);}

async function compressImage(file){const url=URL.createObjectURL(file);try{const img=await new Promise((resolve,reject)=>{const el=new Image();el.onload=()=>resolve(el);el.onerror=()=>reject(new Error('Could not read photo.'));el.src=url;});const target=fitWithin(img.naturalWidth,img.naturalHeight,PHOTO_MAX_EDGE);const canvas=document.createElement('canvas');canvas.width=target.width;canvas.height=target.height;canvas.getContext('2d',{alpha:false}).drawImage(img,0,0,target.width,target.height);const blob=await new Promise((resolve,reject)=>canvas.toBlob((b)=>b?resolve(b):reject(new Error('Compression failed')),'image/jpeg',PHOTO_JPEG_QUALITY));return {blob,width:target.width,height:target.height,mimeType:'image/jpeg'};}finally{URL.revokeObjectURL(url);}}
async function buildBackup(){const data={};for(const store of STORES){data[store]=await Promise.all((await all(store)).map(serialize));}return buildBackupEnvelope(data,new Date().toISOString());}
async function serialize(record){
  if(record===null||typeof record!=='object')return record;
  if(Array.isArray(record))return Promise.all(record.map(serialize));
  const copy={};
  for(const [key,value] of Object.entries(record)){
    if(key==='blob'&&value instanceof Blob){
      copy.blobDataUrl=await new Promise((resolve,reject)=>{const reader=new FileReader();reader.onload=()=>resolve(reader.result);reader.onerror=()=>reject(reader.error);reader.readAsDataURL(value);});
    }else copy[key]=await serialize(value);
  }
  return copy;
}
async function downloadBackup(){const exportedAt=now();const payload=await buildBackup();payload.exportedAt=exportedAt;const json=JSON.stringify(payload,null,2);const filename=`cropchronicle-backup-${exportedAt.slice(0,10)}.json`;const blob=new Blob([json],{type:'application/json'});let shared=false;try{const file=new File([blob],filename,{type:'application/json'});if(navigator.canShare?.({files:[file]})){await navigator.share({files:[file],title:'CropChronicle backup'});shared=true;}}catch(error){if(error?.name==='AbortError')return;}if(!shared){const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download=filename;document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),1000);}const meta=await getMeta();await putProfile({...meta,id:'meta',lastBackupAt:exportedAt,appVersion:APP_VERSION});await refreshBackupStatus();}
async function getMeta(){return (await one('profile','meta'))??{id:'meta'};}
async function getSetup(){return (await one('profile','setup'))??{id:'setup'};}
async function setSetup(changes){const setup=await getSetup();await putProfile({...setup,...changes,id:'setup',updatedAt:now()});}

async function refresh(){const farms=await all('farms');if(!state.farmId&&farms[0])state.farmId=farms[0].id;$('#farms').innerHTML=farms.map((f)=>`<button class="row farm" data-id="${f.id}"><strong>${esc(f.name)}</strong><small>${esc(f.region||'Saved on this phone')}</small></button>`).join('')||'<p class="muted">No farms yet.</p>';document.querySelectorAll('.farm').forEach((el)=>el.addEventListener('click',async()=>{state.farmId=el.dataset.id;state.placeId=null;await refreshPlaces();}));$('#outboxCount').textContent=String((await all('outbox')).length);await refreshBackupStatus();await refreshToday();}
async function refreshPlaces(){const places=state.farmId?await byIndex('places','farmId',state.farmId):[];if(!places.some((p)=>p.id===state.placeId))state.placeId=places[0]?.id??null;$('#places').innerHTML=places.map((p)=>`<button class="row place" data-id="${p.id}"><strong>${esc(p.name)}</strong><small>${esc(placeTypeLabel(p.type))}${p.acreage?` · ${p.acreage} acres`:''}</small></button>`).join('')||'<p class="muted">Choose a farm, then add a Place.</p>';document.querySelectorAll('.place').forEach((el)=>el.addEventListener('click',async()=>{state.placeId=el.dataset.id;await refreshTimeline();}));await refreshTimeline();await fillTaskPlaces();}
let timelineRevision=0,timelinePhotoUrls=[];
async function refreshTimeline(){
  const revision=++timelineRevision,placeId=state.placeId;
  const [events,photos,place]=await Promise.all([
    placeId?byIndex('events','placeId',placeId):[],
    placeId?byIndex('media','placeId',placeId):[],
    placeId?one('places',placeId):null,
  ]);
  if(revision!==timelineRevision)return;
  for(const url of timelinePhotoUrls)URL.revokeObjectURL(url);
  timelinePhotoUrls=[];
  $('#chroniclePlaceLabel').textContent=place?`${place.name} · ${placeTypeLabel(place.type)}`:'Choose a Place';
  const entries=[...events,...photos.map((photo)=>({...photo,occurredAt:photo.createdAt,localPhoto:true}))];
  $('#timeline').innerHTML=sortTimeline(entries).map((entry)=>{
    if(entry.localPhoto){
      if(!(entry.blob instanceof Blob))return '<article class="event">Photo unavailable on this phone.</article>';
      const url=URL.createObjectURL(entry.blob);timelinePhotoUrls.push(url);
      return `<article class="event"><time>${esc(new Date(entry.createdAt).toLocaleString())}</time><strong>Photo</strong><img class="chronicle-photo" src="${url}" alt="Saved photo for this Place" loading="lazy"></article>`;
    }
    return `<article class="event"><time>${esc(new Date(entry.occurredAt).toLocaleString())}</time><strong>${esc(entry.eventType)}</strong><span>${esc(entry.title||entry.notes||'')}</span></article>`;
  }).join('')||'<p class="muted">Choose a Place to see its Chronicle.</p>';
}
async function currentSeason(placeId){const xs=placeId?await byIndex('seasons','placeId',placeId):[];return xs.sort((a,b)=>String(b.year??'').localeCompare(String(a.year??'')))[0]??null;}
async function refreshAlmanac(){const weather=state.farmId?await byIndex('weather_snapshots','farmId',state.farmId):[],refs=state.farmId?await byIndex('reference_layers','farmId',state.farmId):[],latest=weather.slice().sort((a,b)=>String(b.createdAt).localeCompare(String(a.createdAt)))[0]??null,cards=[];if(latest){const temp=latest.values?.temperature,frost=frostContext({temperature:temp});cards.push(almanacCard({kind:'measured',title:'Latest field weather',value:temp===null?'Temperature not recorded':temp+' °F',detail:frost.message,provenance:latest.provenance}));const flags=sprayWeatherFlags({windSpeed:latest.values?.windSpeed,windGust:latest.values?.windGust,precipitation:latest.values?.precipitation,temperature:temp});if(flags.length)cards.push(almanacCard({kind:'measured',title:'Application-weather checks',detail:flags.map(x=>x.message).join(' '),provenance:latest.provenance}));}for(const ref of refs.slice().sort((a,b)=>String(b.createdAt).localeCompare(String(a.createdAt))).slice(0,6))cards.push(almanacCard({kind:ref.kind,title:ref.title,detail:ref.detail,provenance:ref.provenance}));$('#almanacCards').innerHTML=cards.map(c=>{const fresh=c.provenance?sourceFreshness(c.provenance):'unknown',traditional=c.kind==='traditional';return '<article class="intel-item '+(fresh==='stale'?'freshness-stale ':'')+(traditional?'traditional-card':'')+'"><span class="almanac-kind">'+esc(c.label)+'</span><strong>'+esc(c.title)+'</strong>'+(c.value?'<span>'+esc(c.value)+'</span>':'')+(c.detail?'<span>'+esc(c.detail)+'</span>':'')+'<div class="source-line">'+esc(c.provenance?.provider??'No external source')+(c.provenance?.retrievedAt?' · '+esc(new Date(c.provenance.retrievedAt).toLocaleString()):'')+(fresh==='stale'?' · STALE':'')+'</div></article>';}).join('')||'<article class="intel-item"><strong>Offline ready</strong><span>Add a weather observation or Almanac note. Online providers can feed this same sourced format later.</span></article>';}
async function refreshNwsWeather(){if(!state.location)throw new Error('Use Locate me first so CropChronicle knows which forecast point you requested.');$('#providerStatus').textContent='Refreshing National Weather Service forecast…';try{const result=await nwsPointForecast(state.location.lat,state.location.lon),period=result.periods?.[0];if(!period)throw new Error('No forecast period returned.');const snap=nwsPeriodToSnapshot(period,result.provenance,newId('weather')),createdAt=now(),record=createVersioned({...snap,farmId:state.farmId,createdAt,privacy:'private'},createdAt);await putWithOutbox('weather_snapshot',record);$('#providerStatus').textContent='NWS forecast refreshed. Farm GPS was used for this request; saved forecast is private.';await refreshAlmanac();}catch(error){const status=providerStatus(error);$('#providerStatus').textContent='NWS '+status.message+'. Existing farm records and last saved weather remain available.';$('#providerStatus').classList.add('provider-error');throw error;}}
async function saveExperiment(input){const place=state.placeId?await get('places',state.placeId):null;if(!place)throw new Error('Choose a field first.');const createdAt=now(),plan=designFieldExperiment({placeId:place.id,...input}),record=createVersioned({...plan,farmId:state.farmId,privacy:'private',createdAt},createdAt);await putWithOutbox('experiment',record);await createEventFrom({type:'experiment_planned',title:'Field experiment planned',notes:plan.title+' · '+plan.metric,placeId:place.id,occurredAt:createdAt});notifySaved();await refreshMap();}
async function saveApplication(input){const place=state.placeId?await get('places',state.placeId):null;if(!place)throw new Error('Choose a field first.');const a=applicationRecord(input),createdAt=now(),record=createVersioned({id:newId('application'),farmId:state.farmId,placeId:place.id,...a,privacy:'private',createdAt},createdAt);await putWithOutbox('application',record);await createEventFrom({type:'application',title:'Application/input recorded',notes:a.product+(a.rate!=null?' · '+a.rate+' '+a.rateUnit:''),placeId:place.id,occurredAt:a.appliedAt});notifySaved();await refreshMap();}
async function saveHarvest(input){const place=state.placeId?await get('places',state.placeId):null;if(!place)throw new Error('Choose a field first.');const y=normalizeYield({amount:input.amount,unit:input.unit,acres:input.acres}),createdAt=now(),harvestedAt=input.harvestedAt,record=createVersioned({id:newId('harvest'),farmId:state.farmId,placeId:place.id,year:Number(String(harvestedAt).slice(0,4)),harvestedAt,...y,moisture:input.moisture===''?null:Number(input.moisture),notes:String(input.notes||'').trim(),privacy:'private',createdAt},createdAt);await putWithOutbox('harvest',record);await createEventFrom({type:'harvest',title:'Harvest recorded',notes:y.amount+' '+y.unit+(y.perAcre!=null?' · '+y.perAcre.toFixed(2)+' '+y.unit+'/acre':''),placeId:place.id,occurredAt:harvestedAt});notifySaved();await refreshMap();}
async function saveManualWeather(input){if(!state.farmId)throw new Error('Choose or create a farm first.');const createdAt=now(),provenance=buildAgProvenance({provider:'Farmer observation',kind:'farmer-entered',retrievedAt:createdAt,observedAt:createdAt}),snapshot=weatherSnapshot({id:newId('weather'),kind:'measured',temperature:input.temperature,humidity:input.humidity,windSpeed:input.windSpeed,windGust:input.windGust,precipitation:input.precipitation,provenance});const record=createVersioned({...snapshot,farmId:state.farmId,notes:String(input.notes||'').trim(),createdAt,privacy:'private'},createdAt);await putWithOutbox('weather_snapshot',record);notifySaved();await refreshAlmanac();}
async function saveAlmanacNote(input){if(!state.farmId)throw new Error('Choose or create a farm first.');const createdAt=now(),kind=input.kind,provider=String(input.source||'').trim()||'Farmer note',provenance=buildAgProvenance({provider,kind:kind==='measured'?'farmer-entered':kind,retrievedAt:createdAt,observedAt:kind==='measured'?createdAt:null}),record=createVersioned({id:newId('ref'),farmId:state.farmId,kind,title:String(input.title).trim(),detail:String(input.detail).trim(),provenance,privacy:'private',createdAt},createdAt);almanacCard(record);await putWithOutbox('reference_layer',record);notifySaved();await refreshAlmanac();}
async function refreshTodayIntelligence(){if(!state.farmId){$('#todayScorecard').innerHTML='';$('#todayAttention').innerHTML='<span class="muted">Create or choose a farm to see operation-wide attention.</span>';return;}const places=await byIndex('places','farmId',state.farmId),boundaries=await all('boundaries'),seasons=await all('seasons'),tasks=await byIndex('tasks','farmId',state.farmId),scouts=await all('observations'),weatherRows=await byIndex('weather_snapshots','farmId',state.farmId),harvests=await byIndex('harvests','farmId',state.farmId),placeIds=new Set(places.map(x=>x.id)),latestWeather=weatherRows.slice().sort((a,b)=>String(b.createdAt).localeCompare(String(a.createdAt)))[0]??null,today=farmToday({places,boundaries:boundaries.filter(x=>placeIds.has(x.placeId)),seasons:seasons.filter(x=>placeIds.has(x.placeId)),tasks,scouts:scouts.filter(x=>placeIds.has(x.placeId)),weather:latestWeather,harvests});$('#todayScorecard').innerHTML=[['Fields',today.counts.fields],['Open work',today.counts.openTasks],['Attention',today.counts.attention],['Record gaps',today.counts.recordGaps]].map(([label,value])=>'<div class="today-stat"><strong>'+value+'</strong><span>'+label+'</span></div>').join('');$('#todayAttention').innerHTML=today.items.slice(0,30).map(x=>'<div class="attention-row attention-'+esc(x.level)+'"><span class="attention-level">'+esc(x.level.replaceAll('_',' '))+'</span><div><strong>'+esc(x.title)+'</strong><small>'+esc(x.reason)+'</small></div></div>').join('')||'<span class="muted">No attention items from current records.</span>';}
async function refreshMap(){
  const places=state.farmId?await byIndex('places','farmId',state.farmId):[],boundaries=await all('boundaries'),seasons=await all('seasons'),boundaryMap=new Map(boundaries.map(b=>[b.placeId,b]));
  const place=state.placeId?await one('places',state.placeId):places[0]??null;if(place&&!state.placeId)state.placeId=place.id;
  const season=place?await currentSeason(place.id):null,boundary=place?boundaryMap.get(place.id):null,scouts=place?await byIndex('observations','placeId',place.id):[],tasks=place?await byIndex('tasks','placeId',place.id):[],events=place?await byIndex('events','placeId',place.id):[],applicationRows=place?await byIndex('applications','placeId',place.id):[],harvestRows=place?await byIndex('harvests','placeId',place.id):[],weatherRows=state.farmId?await byIndex('weather_snapshots','farmId',state.farmId):[],latestWeather=weatherRows.slice().sort((a,b)=>String(b.createdAt).localeCompare(String(a.createdAt)))[0]??null,intel=fieldIntelligence({place,boundary,season,weather:latestWeather,scouts,tasks,events,layers:{soil:state.soilOverlay,cropContext:state.cropContext,slope:state.slopeOverlay,water:state.waterOverlay}});
  const samples=place?await byIndex('ag_samples','placeId',place.id):[],almanacRows=state.farmId?await byIndex('reference_layers','farmId',state.farmId):[],fieldWeather=weatherRows.filter(x=>x.placeId===place?.id),report=predictiveR2({place,seasons:seasons.filter(x=>x.placeId===place?.id),harvests:harvestRows,applications:applicationRows,samples,scouts,almanac:almanacRows.filter(x=>x.placeId===place?.id),weather:fieldWeather});
  $('#fieldPredictions').innerHTML=place?`<div class="prediction-status"><strong>${esc(report.sufficiency.label)} evidence</strong><span>${report.sufficiency.score}/${report.sufficiency.max} data gates · ${esc(report.suggestionMode.replaceAll('_',' '))}</span></div><p class="muted">Coverage: ${report.coverage.seasons} seasons · ${report.coverage.harvests} harvests · ${report.coverage.applications} applications · ${report.coverage.soilSamples} soil samples · ${report.coverage.weather} field weather records.</p>${report.sufficiency.missing.length?'<p class="muted"><b>Strengthen this model:</b> '+esc(report.sufficiency.missing.join(' · '))+'</p>':''}${report.backtest.status==='evaluated'?'<article class="prediction-card"><strong>Historical holdout check</strong><p>'+report.backtest.summary.holdouts+' season(s) tested against prior comparable yield history'+(report.backtest.summary.meanAbsolutePercentError!=null?' · mean absolute error '+esc(report.backtest.summary.meanAbsolutePercentError.toFixed(1))+'%':'')+'.</p><small>Baseline validation only · no causal or dosing validation</small></article>':'<article class="prediction-card"><strong>Backtest waiting for history</strong><p>At least three comparable harvest records are needed before CropChronicle can hide a season and test against it.</p></article>'}${report.suggestions.map(x=>'<article class="prediction-card"><strong>'+esc(x.title)+'</strong><p>'+esc(x.observation)+'</p><p><b>Possible next step:</b> '+esc(x.nextStep)+'</p><small>'+esc(x.confidence)+' · '+x.evidence.length+' linked records · descriptive, not causal · no automatic rate advice</small></article>').join('')||'<p class="muted">No field patterns identified from available records.</p>'}`:'<p class="muted">Select a field to review patterns.</p>';
  $('#fieldRelationships').innerHTML=place?(report.relationships.relationships.map(r=>'<article class="relationship-card"><strong>'+esc(r.label)+' ↔ yield</strong><span>'+esc(r.strength.replaceAll('_',' '))+' · r='+r.r.toFixed(2)+' · n='+r.n+'</span><small>Exploratory association only; not evidence that changing this factor will change yield.</small></article>').join('')||'<p class="muted">Three or more comparable yield seasons are needed for relationship discovery.</p>'):'';
  $('#mapPlaceTitle').textContent=place?.name??'Choose a field';
  const history=fieldSeasonHistory({seasons:seasons.filter(x=>x.placeId===place?.id),events,harvests:harvestRows,scouts,tasks});const rotation=cropRotation(seasons.filter(x=>x.placeId===place?.id)),trend=yieldTrend(history);$('#rotationStrip').innerHTML=place?rotation.map(r=>`<div class="rotation-year"><strong>${r.year}</strong><span>${esc(r.crop?r.crop.replaceAll('_',' '):'unknown')}</span>${r.variety?'<span>'+esc(r.variety)+'</span>':''}</div>`).join(''):'';const comparable=trend.length&&new Set(trend.map(x=>x.unit)).size===1,maxYield=comparable?Math.max(...trend.map(x=>x.value),1):1;$('#yieldTrend').innerHTML=!place?'':!trend.length?'<span class="muted">No comparable yield history yet.</span>':!comparable?'<span class="muted">Yield history uses different units; chart withheld.</span>':trend.slice().reverse().map(x=>`<div class="yield-bar" title="${esc(x.year+' '+x.value+' '+x.unit)}"><b>${esc(x.value)}</b><i style="height:${Math.max(3,Math.round(x.value/maxYield*90))}px"></i><span>${x.year}</span></div>`).join('');$('#seasonHistory').innerHTML=place?history.map(r=>`<article class="season-card"><h4>${r.year} · ${esc(r.crop?normalizeCrop(r.crop).replaceAll('_',' '):'crop unknown')}</h4><div class="yield">${r.mixedYieldUnits?'Mixed yield units':r.harvestCount?(esc(r.yieldTotal)+' '+esc(r.yieldUnit)):'No harvest recorded'}</div><div class="detail">${r.variety?esc(r.variety)+' · ':''}${r.scoutCount} scouting · ${r.eventCount} Chronicle events</div></article>`).join('')||'<span class="muted">No season history yet.</span>':'';$('#historyNote').textContent=place?historyComparisonNote(history):'';
  $('#fieldSummary').innerHTML=place?`<div class="field-metric"><span>Crop</span><strong>${esc(intel.cropLabel??'Unknown')}</strong></div><div class="field-metric"><span>Acres</span><strong>${esc(intel.acres??'Unknown')}</strong></div><div class="field-metric"><span>Open work</span><strong>${intel.openTasks.length}</strong></div><div class="field-metric"><span>Weather</span><strong>${intel.weather?.temperature!=null?esc(intel.weather.temperature+' °F'):'Unknown'}</strong></div>`:'';
  $('#fieldIntel').innerHTML=place?`<article class="intel-item"><strong>Season</strong><span>${esc(intel.cropLabel??'Crop not set')}${intel.variety?' · '+esc(intel.variety):''}${intel.plantedAt?' · planted '+esc(intel.plantedAt):''}${intel.seasonStatus?' · '+esc(intel.seasonStatus):''}</span></article><article class="intel-item"><strong>Weather & frost context</strong><span>${intel.weather?esc((intel.weather.provider??'Source')+' · '+(intel.weather.freshness??'unknown')+' · '+intel.frost.message):'No sourced weather saved for this farm.'}</span></article><article class="intel-item"><strong>Recent scouting</strong><div class="scout-list">${intel.recentScouts.map(o=>'<div class="scout-row"><strong>'+esc(o.category)+'</strong><span>'+esc(o.severity)+'</span><span>'+esc(o.notes)+'</span></div>').join('')||'<span>No scouting observations yet.</span>'}</div></article><article class="intel-item"><strong>Active public reference layers</strong><div class="layer-state">${Object.entries(intel.layers).filter(([,v])=>v).map(([k])=>'<span>'+esc(k)+'</span>').join('')||'<span>none</span>'}</div></article><article class="intel-item"><strong>Privacy: private</strong><span>Field geometry, scouting and farm records stay private unless explicitly shared. Public map layers remain reference context.</span></article>`:'<span class="muted">Add or choose a Place to begin mapping.</span>';
  const map=$('#fallbackMap');if(!boundary&&!state.boundaryDraft.length)map.innerHTML='<div class="map-empty"><strong>No boundary for this Place yet.</strong><span>Tap Draw boundary, then tap around the field or use your GPS position.</span></div>';else renderBoundaryDraft(boundary?.geometry?.coordinates?.[0]?.map(([lon,lat])=>({lat,lon}))??state.boundaryDraft);
  $('#mapLegend').innerHTML='<span class="legend-label">Crop colors</span>'+CROP_CATEGORIES.slice(0,8).map(c=>`<span class="legend-chip" aria-disabled="true">${esc(c.replaceAll('_',' '))}</span>`).join('');
  const fc=fieldCollection(boundaries.filter(b=>places.some(p=>p.id===b.placeId)),places,seasons);state.mapFeatures=fc;{const host=$('#geoMap');if(!state.geoMap){host.hidden=false;try{state.geoMap=await createFarmMap({container:host,featureCollection:fc,basemapId:state.basemap,center:state.location,onStatus:s=>{$('#providerStatus').textContent=s;},onMapClick:p=>{if(state.boundaryEditing){const next={...p,capturedAt:now()},check=canAppendBoundaryPoint(state.boundaryDraft,next);if(!check.ok){$('#locationStatus').textContent=check.reason==='duplicate'?'That point is too close to an existing boundary point.':check.reason==='crossing'?'That point would cross the field boundary. Continue around the perimeter in order.':'That boundary point is invalid.';return;}state.boundaryDraft.push(next);renderBoundaryDraft(state.boundaryDraft);}},onSelect:async props=>{state.placeId=props.placeId;await refreshMap();}});}catch(error){console.error('CropChronicle geographic map initialization failed',error);state.geoMap=null;}if(state.geoMap){$('#fallbackMap').hidden=true;$('#farmMap').classList.add('map-live');if(!$('#providerStatus').textContent||/unavailable|fallback/i.test($('#providerStatus').textContent))$('#providerStatus').textContent='Loading USGS map…';}else{host.hidden=true;$('#fallbackMap').hidden=false;$('#farmMap').classList.remove('map-live');$('#providerStatus').textContent='Geographic map unavailable · fallback boundary view active';}}else{const src=state.geoMap.getSource?.('farm-fields');if(src?.setData)src.setData(fc);}}
}
function renderBoundaryDraft(points=[]){if(state.geoMap){setBoundaryDraft(state.geoMap,points);$('#geoMap').hidden=false;$('#farmMap').classList.add('map-live');return;}const map=$('#fallbackMap');map.innerHTML='';if(!points.length)return;const lats=points.map(p=>p.lat),lons=points.map(p=>p.lon),minLat=Math.min(...lats),maxLat=Math.max(...lats),minLon=Math.min(...lons),maxLon=Math.max(...lons),latSpan=Math.max(maxLat-minLat,.0001),lonSpan=Math.max(maxLon-minLon,.0001);const toPct=p=>({x:5+90*(p.lon-minLon)/lonSpan,y:95-90*(p.lat-minLat)/latSpan});const svg=document.createElementNS('http://www.w3.org/2000/svg','svg');svg.setAttribute('class','boundary-svg');const poly=document.createElementNS('http://www.w3.org/2000/svg','polygon');poly.setAttribute('points',points.map(p=>{const q=toPct(p);return `${q.x},${q.y}`}).join(' '));svg.append(poly);map.append(svg);for(const p of points){const q=toPct(p),dot=document.createElement('span');dot.className='boundary-point';dot.style.left=q.x+'%';dot.style.top=q.y+'%';map.append(dot);}}
function locateOnce(){return new Promise((resolve,reject)=>{if(!navigator.geolocation)return reject(new Error('Location is not available in this browser.'));navigator.geolocation.getCurrentPosition(p=>resolve({lat:p.coords.latitude,lon:p.coords.longitude,accuracy:p.coords.accuracy,capturedAt:now()}),reject,{enableHighAccuracy:true,timeout:12000,maximumAge:15000});});}
async function saveBoundary(){
  if(!state.placeId)throw new Error('Choose a field or pasture first.');if(state.boundaryDraft.length<3)throw new Error('A boundary needs at least three points.');if(boundarySelfIntersects(state.boundaryDraft))throw new Error('Boundary lines cannot cross. Undo points and continue around the field perimeter in order.');
  const existing=(await byIndex('boundaries','placeId',state.placeId))[0]??null,acres=polygonAreaAcres(state.boundaryDraft),closed=[...state.boundaryDraft,state.boundaryDraft[0]],record=createVersioned({id:existing?.id??newId('boundary'),placeId:state.placeId,geometry:{type:'Polygon',coordinates:[closed.map(p=>[p.lon,p.lat])]},acreageCalculated:Number(acres.toFixed(2)),acreageOverride:existing?.acreageOverride??null,captureMethod:'map_or_gps',privacy:'private',createdAt:existing?.createdAt??now()},now());
  if(existing){record.version=existing.version+1;await putWithOutbox('place_boundary',record,{operation:'update',baseVersion:existing.version});}else await putWithOutbox('place_boundary',record);
  state.boundaryDraft=[];notifySaved();await refreshMap();
}
async function saveSeason(input){
 const place=state.placeId?await one('places',state.placeId):null;if(!place)throw new Error('Choose a field or pasture first.');
 const existing=await currentSeason(place.id),plantedAt=input.plantedAt||'',year=Number((plantedAt||localDateOnly()).slice(0,4)),crop=normalizeCrop(input.crop);
 const record=createVersioned({id:existing?.id??newId('season'),farmId:place.farmId,placeId:place.id,year,crop,variety:String(input.variety||'').trim(),plantedAt:plantedAt||null,status:input.status||'growing',notes:String(input.notes||'').trim(),privacy:'private',createdAt:existing?.createdAt??now()},now());
 if(existing){record.version=existing.version+1;await putWithOutbox('season',record,{operation:'update',baseVersion:existing.version});}else await putWithOutbox('season',record);
 await createEventFrom('season_update','Season: '+(CROP_VISUALS[crop]?.label??crop),record.variety?'Variety / hybrid: '+record.variety:'',place.id);notifySaved();await refreshMap();
}
async function saveScout(input){
 const place=state.placeId?await one('places',state.placeId):null;if(!place)throw new Error('Choose a field or pasture first.');let location=null;
 if(input.useLocation){location=state.location;try{location=await locateOnce();state.location=location;}catch{if(!location)throw new Error('GPS location is unavailable. Uncheck location to save a non-geolocated observation.');}}
 const clean=validateScout({category:input.category,severity:input.severity,notes:input.notes,location}),observedAt=now(),record=createVersioned({id:newId('obs'),farmId:place.farmId,placeId:place.id,...clean,observedAt,privacy:'private',createdAt:observedAt},observedAt);
 await putWithOutbox('observation',record);await createEventFrom('scouting','Scouting: '+clean.category+' ('+clean.severity+')',clean.notes,place.id);notifySaved();await refreshMap();return record;
}
async function refreshToday(){const tasks=await all('tasks'),places=await all('places'),placeMap=new Map(places.map((p)=>[p.id,p]));const grouped=groupTasksForToday(tasks,localDateOnly());renderTasks('#tasksOverdue',grouped.overdue,placeMap,true);renderTasks('#tasksToday',grouped.today,placeMap,false);renderTasks('#tasksNext7',grouped.next7,placeMap,false);}
function renderTasks(selector,tasks,placeMap,overdue){const el=$(selector);el.innerHTML=tasks.map((t)=>{const p=placeMap.get(t.placeId),repeat=t.repeat?.kind&&t.repeat.kind!=='none'?` · repeats ${repeatLabel(t.repeat)}`:'';return `<article class="task-card${overdue?' overdue':''}" data-task="${t.id}"><h4>${esc(t.title)}</h4><div class="task-meta">${esc(p?.name||'Place')} · due ${esc(t.dueDate)}${esc(repeat)}</div>${t.notes?`<p>${esc(t.notes)}</p>`:''}<div class="task-actions"><button class="task-done" data-id="${t.id}">Done</button>${t.repeat?.kind&&t.repeat.kind!=='none'?`<button class="task-skip skip" data-id="${t.id}">Skip</button>`:''}</div></article>`;}).join('')||'<p class="muted">Nothing here.</p>';el.querySelectorAll('.task-done').forEach((b)=>b.addEventListener('click',()=>completeTask(b.dataset.id)));el.querySelectorAll('.task-skip').forEach((b)=>b.addEventListener('click',()=>skipTask(b.dataset.id)));}
function repeatLabel(repeat){if(repeat.kind==='daily')return'daily';if(repeat.kind==='weekly')return'weekly';if(repeat.kind==='monthly')return'monthly';if(repeat.kind==='every_n_days')return`every ${repeat.interval} days`;return'never';}
async function refreshBackupStatus(){const meta=await getMeta();$('#versionLabel').textContent=`Version ${APP_VERSION}`;const age=backupAgeDays(meta.lastBackupAt);$('#lastBackupLabel').textContent=meta.lastBackupAt?`Last backup: ${new Date(meta.lastBackupAt).toLocaleDateString()}`:'Last backup: never';const reminder=$('#backupReminder');if(backupReminderDue(meta.lastBackupAt)){reminder.hidden=false;$('#backupReminderText').textContent=`It has been ${age} days since your last backup. Export one before you forget.`;}else{reminder.hidden=true;}}

async function createFarmFrom(name,region=''){const farm=createVersioned({id:newId('farm'),name,region},now());await putWithOutbox('farm',farm);state.farmId=farm.id;state.placeId=null;notifySaved();await refresh();await refreshPlaces();return farm;}
async function createPlaceFrom(name,type='field',acreage=''){if(!state.farmId){const farms=await all('farms');state.farmId=farms[0]?.id??null;}if(!state.farmId)throw new Error('Create a farm first.');if(!PLACE_TYPES.includes(type))throw new Error('Choose a valid Place type.');const place=createVersioned({id:newId('place'),farmId:state.farmId,name,type,acreage:acreage?Number(acreage):null},now());await putWithOutbox('place',place);state.placeId=place.id;notifySaved();await refreshPlaces();return place;}
async function createEventFrom(eventType,title,notes='',placeId=state.placeId){const place=placeId?await one('places',placeId):null;if(!place)throw new Error('Choose a farm and Place first.');const event=createVersioned({id:newId('event'),farmId:place.farmId,placeId,eventType:eventType||'note',occurredAt:now(),title:title||'',notes:notes||'',privacy:'private',details:{},createdAt:now()},now());await putWithOutbox('event',event);notifySaved();await refreshTimeline();await refresh();return event;}
async function createTaskFrom({title,placeId,dueDate,repeatKind='none',everyNDays=1,notes=''}){const place=await one('places',placeId);if(!place)throw new Error('Choose a Place.');const task=createVersioned({id:newId('task'),seriesId:null,farmId:place.farmId,placeId,title,dueDate,repeat:normalizeRepeat(repeatKind,everyNDays,dueDate),notes,status:'open',createdAt:now()},now());task.seriesId=task.id;await putWithOutbox('task',task);notifySaved();await refreshToday();await refresh();return task;}

async function completeTask(id){const tx=db.transaction(['tasks','events','outbox'],'readwrite'),tasks=tx.objectStore('tasks'),events=tx.objectStore('events'),outbox=tx.objectStore('outbox');const committed=done(tx);let task;try{task=await req(tasks.get(id));if(!task||task.status!=='open'){await committed;return;}const completedAt=now(),today=localDateOnly(),updated=updateVersioned(task,{status:'done',completedAt},completedAt),event=createVersioned({id:newId('event'),farmId:task.farmId,placeId:task.placeId,eventType:'task_done',occurredAt:completedAt,title:`Task done: ${task.title}`,notes:task.notes||'',privacy:'private',details:{taskId:task.id},createdAt:completedAt},completedAt);const nextDue=nextRepeatDue(task.dueDate,task.repeat,today);tasks.put(updated);events.put(event);outbox.put(makeOutboxMutation('task',updated,'update',task.version,completedAt));outbox.put(makeOutboxMutation('event',event,'create',null,completedAt));if(nextDue){const nextTask=createVersioned({id:newId('task'),seriesId:task.seriesId||task.id,farmId:task.farmId,placeId:task.placeId,title:task.title,dueDate:nextDue,repeat:task.repeat,notes:task.notes||'',status:'open',createdAt:completedAt},completedAt);tasks.put(nextTask);outbox.put(makeOutboxMutation('task',nextTask,'create',null,completedAt));}await committed;}catch(error){try{tx.abort();}catch{}await committed.catch(()=>{});throw error;}notifySaved();await refreshToday();if(state.placeId===task.placeId)await refreshTimeline();await refresh();}
async function skipTask(id){const tx=db.transaction(['tasks','outbox'],'readwrite'),tasks=tx.objectStore('tasks'),outbox=tx.objectStore('outbox');const committed=done(tx);let task;try{task=await req(tasks.get(id));if(!task||task.status!=='open'){await committed;return;}const skippedAt=now(),today=localDateOnly(),updated=updateVersioned(task,{status:'skipped',skippedAt},skippedAt),nextDue=nextRepeatDue(task.dueDate,task.repeat,today);tasks.put(updated);outbox.put(makeOutboxMutation('task',updated,'update',task.version,skippedAt));if(nextDue){const nextTask=createVersioned({id:newId('task'),seriesId:task.seriesId||task.id,farmId:task.farmId,placeId:task.placeId,title:task.title,dueDate:nextDue,repeat:task.repeat,notes:task.notes||'',status:'open',createdAt:skippedAt},skippedAt);tasks.put(nextTask);outbox.put(makeOutboxMutation('task',nextTask,'create',null,skippedAt));}await committed;}catch(error){try{tx.abort();}catch{}await committed.catch(()=>{});throw error;}notifySaved();await refreshToday();await refresh();}

function refreshFarmChrome(){const farms=Array.isArray(state.farms)?state.farms:[],places=Array.isArray(state.places)?state.places:[],seasons=Array.isArray(state.seasons)?state.seasons:[];const farm=state.farmId?farms.find(f=>f.id===state.farmId):null,place=state.placeId?places.find(p=>p.id===state.placeId):null;const farmEl=$('#sidebarFarm'),placeEl=$('#sidebarPlace'),fieldsEl=$('#sidebarFields'),cropsEl=$('#sidebarCrops');if(farmEl)farmEl.textContent=farm?.name||'My Farm';if(placeEl)placeEl.textContent=place?.name||'Select a field';if(fieldsEl)fieldsEl.textContent=places.filter(p=>!state.farmId||p.farmId===state.farmId).length;if(cropsEl)cropsEl.textContent=new Set(seasons.filter(s=>!state.farmId||s.farmId===state.farmId).map(s=>s.crop).filter(Boolean)).size;}function wireFarmChrome(){document.querySelectorAll('[data-jump]').forEach(b=>b.addEventListener('click',()=>switchView(b.dataset.jump)));const actionMap={scout:'#addScout',application:'#addApplication',harvest:'#addHarvest',experiment:'#planExperiment',weather:'#addWeatherSnapshot',backup:'#exportBackup'};document.querySelectorAll('[data-action]').forEach(b=>b.addEventListener('click',()=>{const target=$(actionMap[b.dataset.action]);if(target){if(b.dataset.action!=='backup')switchView('map');target.click();}}));}
function switchView(name){refreshFarmChrome();state.view=name;document.querySelectorAll('.view').forEach((v)=>v.hidden=v.id!==`view${name.charAt(0).toUpperCase()+name.slice(1)}`);document.querySelectorAll('.tab').forEach((b)=>b.classList.toggle('active',b.dataset.view===name));if(name==='map'){refreshMap();refreshAlmanac();}if(name==='today')refreshToday();if(name==='chronicle')refreshTimeline();}
document.querySelectorAll('.tab').forEach((b)=>b.addEventListener('click',()=>switchView(b.dataset.view)));
$('#locateMe').addEventListener('click',async()=>{try{const p=await locateOnce();state.location=p;if(state.geoMap)state.geoMap.flyTo?.({center:[p.lon,p.lat],zoom:16});$('#locationStatus').textContent=`Located to about ${Math.round(p.accuracy)} m. Coordinates remain private on this device.`;if(state.boundaryEditing){state.boundaryDraft.push(p);renderBoundaryDraft(state.boundaryDraft);}}catch(error){$('#locationStatus').textContent=`Location unavailable: ${error.message||'permission denied'}`;}});
$('#mapAddBoundary').addEventListener('click',()=>{if(!state.placeId)return alert('Choose a field or pasture in Places first.');state.boundaryEditing=true;state.boundaryDraft=[];$('#locationStatus').textContent='Boundary mode: tap the geographic map to add points, or Locate me while walking the boundary.';$('#fallbackMap').innerHTML='';renderBoundaryDraft(state.boundaryDraft);});
$('#farmMap').addEventListener('click',(e)=>{if(!state.placeId||!state.boundaryEditing||state.geoMap)return;if(!state.boundaryDraft.length&&e.target.closest('.map-empty'))state.boundaryDraft=[];const r=e.currentTarget.getBoundingClientRect();if(!state.location)return;const metersPerDegLat=111132.92,metersPerDegLon=111412.84*Math.cos(state.location.lat*Math.PI/180),spanM=500,dx=(e.clientX-r.left)/r.width-.5,dy=.5-(e.clientY-r.top)/r.height;state.boundaryDraft.push({lat:state.location.lat+dy*spanM/metersPerDegLat,lon:state.location.lon+dx*spanM/metersPerDegLon,capturedAt:now()});renderBoundaryDraft(state.boundaryDraft);});
$('#mapUndoPoint').addEventListener('click',()=>{if(!state.boundaryEditing)return;state.boundaryDraft.pop();renderBoundaryDraft(state.boundaryDraft);});
$('#mapSaveBoundary').addEventListener('click',async()=>{try{await saveBoundary();state.boundaryEditing=false;state.boundaryDraft=[];renderBoundaryDraft([]);await refreshMap();}catch(error){alert(error.message);}});
$('#mapOpenChronicle').addEventListener('click',()=>switchView('chronicle'));
$('#refreshWeather').addEventListener('click',async()=>{try{await refreshNwsWeather();}catch(error){alert(error.message);}});$('#basemapSelect').addEventListener('change',(e)=>{state.basemap=e.target.value;if(state.geoMap){setBasemap(state.geoMap,state.basemap,state.mapFeatures);setTimeout(()=>{if(state.soilOverlay)setSoilOverlay(state.geoMap,true);if(state.cropContext)setCropContext(state.geoMap,true,2025);if(state.slopeOverlay)setSlopeOverlay(state.geoMap,true);if(state.waterOverlay)setWaterOverlay(state.geoMap,true);},250);}$('#providerStatus').textContent=state.basemap==='none'?'Fields-only map selected.':'USGS basemap selected; online imagery/topography is reference context, not a farm record.';});$('#soilLayerToggle').addEventListener('change',(e)=>{state.soilOverlay=e.target.checked;if(state.geoMap)setSoilOverlay(state.geoMap,state.soilOverlay);$('#providerStatus').textContent=state.soilOverlay?'USDA NRCS Soil Data Access overlay on. Soil polygons are reference data; verify against current survey details and field sampling.':'USDA soil overlay off.';});
$('#cropContextToggle').addEventListener('change',(e)=>{state.cropContext=e.target.checked;if(state.geoMap)setCropContext(state.geoMap,state.cropContext,2025);$('#providerStatus').textContent=state.cropContext?'USDA NASS 2025 Cropland Data Layer on — satellite-derived public crop classification, not live farmer records.':'USDA crop context off.';});
$('#slopeLayerToggle').addEventListener('change',(e)=>{state.slopeOverlay=e.target.checked;if(state.geoMap)setSlopeOverlay(state.geoMap,state.slopeOverlay);$('#providerStatus').textContent=state.slopeOverlay?'USGS 3DEP slope reference on. Terrain model is reference context; verify drainage and field conditions on site.':'Slope layer off.';});
$('#waterLayerToggle').addEventListener('change',(e)=>{state.waterOverlay=e.target.checked;if(state.geoMap)setWaterOverlay(state.geoMap,state.waterOverlay);$('#providerStatus').textContent=state.waterOverlay?'USGS hydrography reference on. This is not a water-rights, flood-risk, or current-flow determination.':'Surface-water layer off.';});
$('#planExperiment').addEventListener('click',()=>{if(!state.placeId)return alert('Choose a field first.');$('#experimentYear').value=new Date().getFullYear();$('#experimentDialog').showModal();});$('#cancelExperiment').addEventListener('click',()=>$('#experimentDialog').close());$('#experimentForm').addEventListener('submit',async(e)=>{e.preventDefault();try{await saveExperiment({seasonYear:Number($('#experimentYear').value),title:$('#experimentTitle').value.trim(),hypothesis:$('#experimentHypothesis').value.trim(),treatment:$('#experimentTreatment').value.trim(),control:$('#experimentControl').value.trim(),metric:$('#experimentMetric').value.trim()});$('#experimentDialog').close();e.target.reset();}catch(error){alert(error.message);}});
$('#addApplication').addEventListener('click',()=>{if(!state.placeId)return alert('Choose a field first.');$('#applicationDate').value=new Date().toISOString().slice(0,10);$('#applicationDialog').showModal();});$('#cancelApplication').addEventListener('click',()=>$('#applicationDialog').close());$('#applicationForm').addEventListener('submit',async(e)=>{e.preventDefault();try{await saveApplication({appliedAt:$('#applicationDate').value,category:$('#applicationCategory').value,product:$('#applicationProduct').value,rate:$('#applicationRate').value,rateUnit:$('#applicationRateUnit').value,totalAmount:$('#applicationTotal').value,notes:$('#applicationNotes').value});$('#applicationDialog').close();}catch(error){alert(error.message);}});
$('#addHarvest').addEventListener('click',()=>{if(!state.placeId)return alert('Choose a field first.');$('#harvestDate').value=new Date().toISOString().slice(0,10);$('#harvestDialog').showModal();});$('#cancelHarvest').addEventListener('click',()=>$('#harvestDialog').close());$('#harvestForm').addEventListener('submit',async(e)=>{e.preventDefault();try{await saveHarvest({harvestedAt:$('#harvestDate').value,amount:$('#harvestAmount').value,unit:$('#harvestUnit').value,acres:$('#harvestAcres').value,moisture:$('#harvestMoisture').value,notes:$('#harvestNotes').value});$('#harvestDialog').close();}catch(error){alert(error.message);}});
$('#addWeatherSnapshot').addEventListener('click',()=>$('#weatherDialog').showModal());$('#cancelWeather').addEventListener('click',()=>$('#weatherDialog').close());$('#weatherForm').addEventListener('submit',async(e)=>{e.preventDefault();try{await saveManualWeather({temperature:$('#weatherTemp').value,humidity:$('#weatherHumidity').value,windSpeed:$('#weatherWind').value,windGust:$('#weatherGust').value,precipitation:$('#weatherPrecip').value,notes:$('#weatherNotes').value});$('#weatherDialog').close();}catch(error){alert(error.message);}});
$('#addAlmanacNote').addEventListener('click',()=>$('#almanacNoteDialog').showModal());$('#cancelAlmanacNote').addEventListener('click',()=>$('#almanacNoteDialog').close());$('#almanacNoteForm').addEventListener('submit',async(e)=>{e.preventDefault();try{await saveAlmanacNote({kind:$('#almanacKind').value,title:$('#almanacTitle').value,detail:$('#almanacDetail').value,source:$('#almanacSource').value});$('#almanacNoteDialog').close();}catch(error){alert(error.message);}});
$('#setSeason').addEventListener('click',async()=>{if(!state.placeId)return alert('Choose a field or pasture first.');const current=await currentSeason(state.placeId);$('#seasonCrop').innerHTML=CROP_CATEGORIES.map(c=>'<option value="'+c+'">'+esc(CROP_VISUALS[c]?.label??c)+'</option>').join('');$('#seasonCrop').value=current?.crop??'corn';$('#seasonVariety').value=current?.variety??'';$('#seasonPlanted').value=current?.plantedAt??'';$('#seasonStatus').value=current?.status??'growing';$('#seasonNotes').value=current?.notes??'';$('#seasonDialog').showModal();});
$('#cancelSeason').addEventListener('click',()=>$('#seasonDialog').close());
$('#seasonForm').addEventListener('submit',async(e)=>{e.preventDefault();try{await saveSeason({crop:$('#seasonCrop').value,variety:$('#seasonVariety').value,plantedAt:$('#seasonPlanted').value,status:$('#seasonStatus').value,notes:$('#seasonNotes').value});$('#seasonDialog').close();}catch(error){alert(error.message);}});
$('#addScout').addEventListener('click',()=>{if(!state.placeId)return alert('Choose a field or pasture first.');$('#scoutNotes').value='';$('#scoutDialog').showModal();});
$('#cancelScout').addEventListener('click',()=>$('#scoutDialog').close());
$('#scoutForm').addEventListener('submit',async(e)=>{e.preventDefault();try{await saveScout({category:$('#scoutCategory').value,severity:$('#scoutSeverity').value,notes:$('#scoutNotes').value,useLocation:$('#scoutUseLocation').checked});$('#scoutDialog').close();}catch(error){alert(error.message);}});
$('#addFarm').addEventListener('click',async()=>{const name=prompt('Farm name');if(!name)return;await createFarmFrom(name,prompt('Region (optional)')||'');});
$('#addPlace').addEventListener('click',async()=>{if(!state.farmId)return alert('Choose or create a farm first.');const name=prompt('Place name');if(!name)return;const type=prompt('Type: field, greenhouse, barn, pasture, or herd/pen','field')||'field';if(!PLACE_TYPES.includes(type))return alert('Use: field, greenhouse, barn, pasture, or herd/pen.');await createPlaceFrom(name,type,prompt('Acres (optional)')||'');});
$('#addEvent').addEventListener('click',async()=>{if(!state.placeId||!state.farmId)return alert('Choose a farm and Place first.');await createEventFrom(prompt('Event type','observation')||'note',prompt('Short title')||'',prompt('Notes')||'');});
$('#photoInput').addEventListener('change',async(e)=>{if(!state.placeId||!state.farmId){e.target.value='';return alert('Choose a farm and Place first.');}const file=e.target.files?.[0];if(!file)return;const placeId=state.placeId,place=await one('places',placeId);if(!place)throw new Error('Choose a Place.');const c=await compressImage(file);const media=createVersioned({id:newId('media'),farmId:place.farmId,placeId,localName:file.name,mimeType:c.mimeType,width:c.width,height:c.height,blob:c.blob,createdAt:now()},now());await putWithOutbox('media',media);$('#photoStatus').textContent=`Saved on this phone at ${c.width}×${c.height}`;notifySaved();e.target.value='';await refresh();await refreshTimeline();});
$('#exportBackup').addEventListener('click',downloadBackup);$('#backupNow').addEventListener('click',downloadBackup);$('#showInstall').addEventListener('click',()=>$('#installGuide').showModal());$('#closeInstall').addEventListener('click',()=>$('#installGuide').close());

async function fillTaskPlaces(){const places=await all('places');$('#taskPlace').innerHTML=places.map((p)=>`<option value="${p.id}">${esc(p.name)} — ${esc(placeTypeLabel(p.type))}</option>`).join('');if(state.placeId)$('#taskPlace').value=state.placeId;}
$('#addTask').addEventListener('click',async()=>{await fillTaskPlaces();if(!$('#taskPlace').options.length)return alert('Add a Place before creating a task.');$('#taskDue').value=localDateOnly();$('#taskTitle').value='';$('#taskNotes').value='';$('#taskRepeat').value='none';$('#taskIntervalWrap').hidden=true;$('#taskDialog').showModal();});
$('#cancelTask').addEventListener('click',()=>$('#taskDialog').close());
$('#taskRepeat').addEventListener('change',()=>{$('#taskIntervalWrap').hidden=$('#taskRepeat').value!=='every_n_days';});
$('#taskForm').addEventListener('submit',async(e)=>{e.preventDefault();await createTaskFrom({title:$('#taskTitle').value.trim(),placeId:$('#taskPlace').value,dueDate:$('#taskDue').value,repeatKind:$('#taskRepeat').value,everyNDays:$('#taskInterval').value,notes:$('#taskNotes').value.trim()});$('#taskDialog').close();switchView('today');});

const installPictures=`<div class="install-pictures"><figure><div class="phone-pic"><div class="safari-bar">cropchronicle.pages.dev</div><div class="share-box">⇧</div></div><figcaption>Tap Safari's Share button.</figcaption></figure><figure><div class="phone-pic"><div class="menu-line">Copy</div><div class="menu-line">Bookmark</div><div class="menu-line highlight">＋ Add to Home Screen</div></div><figcaption>Choose “Add to Home Screen”.</figcaption></figure><figure><div class="phone-pic center"><div class="app-icon">CC</div><strong>CropChronicle</strong><div class="add-pill">Add</div></div><figcaption>Tap Add, then open the new icon.</figcaption></figure></div>`;
async function buildWizardSteps(){const setup=await getSetup(),farms=await all('farms'),places=await all('places'),events=await all('events');if(farms[0]&&!state.farmId)state.farmId=farms[0].id;if(!state.placeId)state.placeId=places.find((p)=>p.farmId===state.farmId)?.id??null;const steps=[];if(!setup.welcomeDone)steps.push('welcome');if(!setup.installDone)steps.push('install');if(farms.length===0)steps.push('farm');if(places.length===0)steps.push('place');if(events.length===0)steps.push('event');return steps;}
async function startFirstRun(){state.wizardSteps=await buildWizardSteps();state.wizardStep=0;if(state.wizardSteps.length){renderWizard();$('#firstRun').showModal();}}
function renderWizard(){const type=state.wizardSteps[state.wizardStep];$('#wizardCount').textContent=`Step ${state.wizardStep+1} of ${state.wizardSteps.length}`;$('#wizardBack').hidden=state.wizardStep===0;$('#wizardNext').textContent=type==='event'?'Save first event':'Continue';const title=$('#wizardTitle'),body=$('#wizardBody');if(type==='welcome'){title.textContent='Welcome to CropChronicle';body.innerHTML='<p>This is a simple farm notebook and task list that keeps working when your signal does not. Your work stays on this phone.</p>';}if(type==='install'){title.textContent='Add CropChronicle to your Home Screen';body.innerHTML=`<p>For the easiest field use, add it once from Safari.</p>${installPictures}<label><input id="installedCheck" type="checkbox"> I added it, or I understand how to do it later.</label>`;}if(type==='farm'){title.textContent='Name your farm';body.innerHTML='<label>Farm name<input id="wizFarmName" autocomplete="organization" placeholder="Example: Demo Acres"></label><label>Region (optional)<input id="wizFarmRegion" placeholder="Example: Central PA"></label>';}if(type==='place'){title.textContent='Add your first Place';body.innerHTML=`<label>Place name<input id="wizPlaceName" placeholder="Example: North 40"></label><label>Type<select id="wizPlaceType">${PLACE_TYPES.map((t)=>`<option value="${t}">${placeTypeLabel(t)}</option>`).join('')}</select></label><label>Acres (optional)<input id="wizPlaceAcres" inputmode="decimal" placeholder="40"></label>`;}if(type==='event'){title.textContent='Record your first event';body.innerHTML='<label>What happened?<select id="wizEventType"><option>observation</option><option>planting</option><option>application</option><option>field_work</option><option>harvest</option><option>note</option></select></label><label>Short title<input id="wizEventTitle" placeholder="Example: Planted corn"></label><label>Notes<textarea id="wizEventNotes" placeholder="Anything you want to remember"></textarea></label>';}}
$('#wizardBack').addEventListener('click',()=>{if(state.wizardStep>0){state.wizardStep--;renderWizard();}});
$('#wizardNext').addEventListener('click',async()=>{const type=state.wizardSteps[state.wizardStep];try{if(type==='welcome')await setSetup({welcomeDone:true});if(type==='install'){if(!$('#installedCheck')?.checked)return alert('Check the box when you are ready to continue.');await setSetup({installDone:true});}if(type==='farm'){const name=$('#wizFarmName').value.trim();if(!name)return alert('Enter your farm name.');await createFarmFrom(name,$('#wizFarmRegion').value.trim());}if(type==='place'){const name=$('#wizPlaceName').value.trim();if(!name)return alert('Enter a Place name.');await createPlaceFrom(name,$('#wizPlaceType').value,$('#wizPlaceAcres').value.trim());}if(type==='event'){const title=$('#wizEventTitle').value.trim();if(!title)return alert('Add a short title.');await createEventFrom($('#wizEventType').value,title,$('#wizEventNotes').value.trim());}state.wizardSteps=await buildWizardSteps();state.wizardStep=0;if(!state.wizardSteps.length){$('#firstRun').close();switchView('today');return;}renderWizard();}catch(error){alert(error.message||'Could not save.');}});

if('serviceWorker'in navigator)navigator.serviceWorker.register('./sw.js');await refresh();await refreshPlaces();await refreshTimeline();await refreshMap();await refreshAlmanac();wireFarmChrome();refreshFarmChrome();switchView('map');await startFirstRun();
function esc(v){return String(v).replace(/[&<>'"]/g,(ch)=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[ch]));}
